name: Auto Run Bot
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install System Tools (สร้างหน้าจอจำลอง)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          
      - name: Install Python Packages
        run: |
          pip install requests beautifulsoup4 undetected-chromedriver selenium
        
      - name: Run Python Code
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_TO_ID: ${{ secrets.LINE_TO_ID }}
        # รันโค้ดผ่านหน้าจอจำลอง (xvfb) ข้ามการตรวจจับ
        run: xvfb-run -a python main.py
        
      - name: Save Data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          touch data.json
          git add data.json
          git commit -m "update data" || echo "No changes"
          git push
